#!/usr/bin/python

""" Script to estimate initial values for CFD Simulations"""


def calc_reynolds_number(length: float, velocity: float, kinematic_viscosity: float, ):
    reynolds_number = length * velocity / kinematic_viscosity
    return reynolds_number


def calc_turb_intensity(reynolds_number: float):
    turb_coefficient = 0.16
    turb_intensity = turb_coefficient * reynolds_number ** (-1/8)
    return turb_intensity


def calc_turb_kinetic_energy(velocity: float, turb_intensity: float):
    turbulent_kinetic_energy = (3 / 2) * (velocity * turb_intensity) ** 2
    return turbulent_kinetic_energy


def calc_turb_length_scale(hydraulic_diameter: float):
    coefficient_for_pipe_flow = 0.07
    turbulent_length_scale = hydraulic_diameter * coefficient_for_pipe_flow
    return turbulent_length_scale


def calc_turb_dissipation_rate(turbulent_kinetic_energy: float, turbulent_length_scale: float):
    constant = 0.09
    epsilon = constant ** (3 / 4) * turbulent_kinetic_energy ** (3 / 2) / turbulent_length_scale
    return epsilon


def calc_specific_turb_dissipation_rate(turbulent_kinetic_energy: float, turbulent_length_scale: float):
    constant = 0.09
    omega = turbulent_kinetic_energy ** 0.5 / (constant ** (1 / 4) * turbulent_length_scale)
    return omega


def calc_turb_viscosity_epsilon(turb_kinetic_energy: float, turb_dissipation_rate: float):
    constant = 0.09
    turbulent_viscosity = constant * turb_kinetic_energy ** 2 / turb_dissipation_rate
    return turbulent_viscosity


def calc_turb_viscosity_omega(turb_kinetic_energy: float, specific_turb_dissipation_rate: float):
    turbulent_viscosity = turb_kinetic_energy / specific_turb_dissipation_rate
    return turbulent_viscosity


def get_metric(prompt: str):
    try:
        metric = float(input(prompt))
        if metric < 0:
            raise ValueError("Value must be positive")
        return metric
    except ValueError as e:
        print(f"Error: {e}")
        exit()


def get_flow_metrics():
    hydraulic_diameter = get_metric("Enter the hydraulic diameter (m): ")
    free_stream_velocity = get_metric("Enter the free stream velocity (m/s): ")
    print("Kinematic viscosity (m²/s): ~1e-6 (water), ~1.48e-5 (air)")
    kinematic_viscosity = get_metric("Enter the kinematic viscosity (m²/s): ")
    return hydraulic_diameter, free_stream_velocity, kinematic_viscosity


def main():
    print('Beginning estimation of initial field and boundary values')
    hydraulic_diameter, free_stream_velocity, kinematic_viscosity = get_input()

    reynolds_number = calc_reynolds_number(hydraulic_diameter, free_stream_velocity, kinematic_viscosity)
    turb_intensity = calc_turb_intensity(reynolds_number)
    turb_kinetic_energy = calc_turb_kinetic_energy(free_stream_velocity, turb_intensity)
    turb_length_scale = calc_turb_length_scale(hydraulic_diameter)
    turb_dissipation_rate = calc_turb_dissipation_rate(turb_kinetic_energy, turb_length_scale)
    specific_turb_dissipation_rate = calc_specific_turb_dissipation_rate(turb_kinetic_energy, turb_length_scale)
    turb_viscosity = calc_turb_viscosity_epsilon(turb_kinetic_energy, turb_dissipation_rate)

    print(f'Hydraulic diameter (D) = {hydraulic_diameter}')
    print(f'Free-stream velocity (U) = {free_stream_velocity}')
    print(f'Kinematic viscosity (ν)= {kinematic_viscosity}')
    print(f'Reynolds Number (Re) = {reynolds_number}')
    print(f'Turbulence intensity (I) = {turb_intensity}')
    print(f'Turbulence kinetic energy (k) = {turb_kinetic_energy}')
    print(f'Turbulence length scale (L) = {turb_length_scale}')
    print(f'Turbulence dissipation rate (ε / epsilon) = {turb_dissipation_rate}')
    print(f'Specific turbulence dissipation rate (ω / omega) = {specific_turb_dissipation_rate}')
    print(f'Turbulent viscosity for k-ε = {turb_viscosity}')

    results = dict()
    results['hydraulic_diameter'] = hydraulic_diameter
    results['free_stream_velocity'] = free_stream_velocity
    results['kinematic_viscosity'] = kinematic_viscosity
    results['reynolds_number'] = reynolds_number
    results['turb_intensity'] = turb_intensity
    results['turb_kinetic_energy'] = turb_kinetic_energy
    results['turb_length_scale'] = turb_length_scale
    results['turb_dissipation_rate'] = turb_dissipation_rate
    results['specific_turb_dissipation_rate'] = specific_turb_dissipation_rate
    results['turb_viscosity'] = turb_viscosity

    return results

if __name__ == "__main__":
    main()



