#!/bin/bash

# Remove all processor directories (from a previous parallel run)
rm -r processor* ???

# Decompose the domain for parallel computing
decomposePar

# Monitor the run using pyFoam
# pyFoamPlotRunner.py 

# Run the simulation in parallel and display output on the screen
foamJob -parallel -screen simpleFoam
