#!/bin/bash

# Remove all processor directories (from a previous parallel run)
rm -r processor* ???

# Decompose the domain for parallel computing
decomposePar

# Renumber the mesh for better convergence (not usable with cyclics!)
renumberMesh -overwrite -constant

# Monitor the run using pyFoam
# pyFoamPlotRunner.py 

# Run the simulation in parallel and display output on the screen
foamJob -parallel -screen pimpleFoam

