#!/bin/bash

# Convert internal faces to baffles
createBaffles -overwrite 2>&1 | tee log.createBaffles;

# Split the newly created baffles
splitBaffles -overwrite 2>&1 | tee -a log.createNCC;

# Create Non-Conformal Couples from baffles
createNonConformalCouples -overwrite 2>&1 | tee -a log.createNCC;
