#!/bin/bash

# Exit if 'constant' or 'system' directories are missing
[ -d "constant" ] || { echo "ERROR: 'constant' directory is missing."; exit 1; }
[ -d "system" ] || { echo "ERROR: 'system' directory is missing."; exit 1; }

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Copy propeller surfaces from resources directory
cp $FOAM_TUTORIALS/resources/geometry/propeller*.obj.gz constant/geometry/

# Remove previous time steps
foco deleteTimeSteps

# Remove previous mesh artifacts
foco deleteMesh

# Generate the background computational mesh from blockMeshDict
runApplication blockMesh

# Extract feature edges from the surface geometry for better meshing
runApplication surfaceFeatures

# Decompose the domain for parallel execution based on decomposeParDict
runApplication decomposePar -noFields

# Run snappyHexMesh in parallel
runParallel snappyHexMesh -overwrite

# Remove meshing directories
rm -r processor*

# Run checkMesh and save the results to a new log
checkMesh 2>&1 | tee log.checkMesh
